backend:
  name: gitub
  repo: mralbor/blog
  

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Posts
    folder: blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown } 